### ISSUE TITLE
Generating code throws NoClassDefFoundError in SQL Developer 4.0.3

### ISSUE THREAD

**Issue by PhilippSalvisberg** [oddgen/oddgen#51]
Nothing happens when calling the generator in SQL Developer 4.0.3. In the log the following is found:

```
#generateToString([org.oddgen.sqldev.model.GeneratorSelection@cfbc9bf], oracle.jdbc.driver.T4CConnection@6641e5d1): thrown java.lang.NoClassDefFoundError(org/oddgen/sqldev/OddgenNavigatorController$9) out of org.oddgen.sqldev.OddgenNavigatorController#generateToString_aroundBody10[247] in 2ms
```

Extension works in 4.1.0, 4.1.1, 4.1.3, 4.1.5, 4.2.0, 17.2.0 - these versions of SQL Developer are based on JDK8. 

JDK7 incompatibility?

**Comment by PhilippSalvisberg** [comment]
The code generated by Xtend uses ```java.util.function.Consumer``` which requires Java 8.
JDK8 should be used for tests only. The current build configuration uses JDK8 to compile all source (test and non-test), hence new API calls are generated by Xtend.

The test cases use the Oracle JDBC driver and the only driver distributed with SQLDev 17.2 is in ojdbc8.jar. And this library requires JDK 8.

A solution is to use JDK7 to compile everything and provide the path to an ojdbc6.jar at build time. But this complicates the building process.

Another solution is to drop the support for SQLDev versions using JDK7 (versions < 4.1.0).

**Comment by PhilippSalvisberg** [comment]
Adjusted release info for v0.3.0. SQLDev 4.1.0 or higher is required.
